//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", ConfigurationName="WebManagement_Port")]
public interface WebManagement_Port
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:InsertWebBasket", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<InsertWebBasket_Result> InsertWebBasketAsync(InsertWebBasket request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:DeleteWebBasket", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<DeleteWebBasket_Result> DeleteWebBasketAsync(DeleteWebBasket request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:InsertSellout", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<InsertSellout_Result> InsertSelloutAsync(InsertSellout request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:DeleteSellout", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<DeleteSellout_Result> DeleteSelloutAsync(DeleteSellout request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:EnterCounter", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<EnterCounter_Result> EnterCounterAsync(EnterCounter request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:CreateSOfromWB", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateSOfromWB_Result> CreateSOfromWBAsync(CreateSOfromWB request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:CreateSOfromWBforUser", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateSOfromWBforUser_Result> CreateSOfromWBforUserAsync(CreateSOfromWBforUser request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:CreateTOfromWBforUser", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateTOfromWBforUser_Result> CreateTOfromWBforUserAsync(CreateTOfromWBforUser request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:CreateAntrepo", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateAntrepo_Result> CreateAntrepoAsync(CreateAntrepo request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:HashPassword", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<HashPassword_Result> HashPasswordAsync(HashPassword request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:ValidateUser", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<ValidateUser_Result> ValidateUserAsync(ValidateUser request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:ChangePassword", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<ChangePassword_Result> ChangePasswordAsync(ChangePassword request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:RandomChangePassword", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<RandomChangePassword_Result> RandomChangePasswordAsync(RandomChangePassword request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:ConfirmWebBasket", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<ConfirmWebBasket_Result> ConfirmWebBasketAsync(ConfirmWebBasket request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:FindItemSerial", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<FindItemSerial_Result> FindItemSerialAsync(FindItemSerial request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:CreateWarReqEntry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateWarReqEntry_Result> CreateWarReqEntryAsync(CreateWarReqEntry request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:UpdateWarReqEntry", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<UpdateWarReqEntry_Result> UpdateWarReqEntryAsync(UpdateWarReqEntry request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:CreateReport_50018", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateReport_50018_Result> CreateReport_50018Async(CreateReport_50018 request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:CreateReport_50162", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<CreateReport_50162_Result> CreateReport_50162Async(CreateReport_50162 request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/WebManagement:SendResourcePassword", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
    System.Threading.Tasks.Task<SendResourcePassword_Result> SendResourcePasswordAsync(SendResourcePassword request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="InsertWebBasket", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class InsertWebBasket
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string aUserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string itemNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public decimal quantity;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public string salesDescription;
    
    public InsertWebBasket()
    {
    }
    
    public InsertWebBasket(string aUserID, string itemNo, decimal quantity, string salesDescription)
    {
        this.aUserID = aUserID;
        this.itemNo = itemNo;
        this.quantity = quantity;
        this.salesDescription = salesDescription;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="InsertWebBasket_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class InsertWebBasket_Result
{
    
    public InsertWebBasket_Result()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteWebBasket", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class DeleteWebBasket
{
    
    public DeleteWebBasket()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteWebBasket_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class DeleteWebBasket_Result
{
    
    public DeleteWebBasket_Result()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="InsertSellout", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class InsertSellout
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string customerNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string itemNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public decimal quantity;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public string name;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    public string contactName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=5)]
    public string address;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=6)]
    public string address2;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=7)]
    public string phoneNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=8)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime invoiceDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=9)]
    public string serialNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=10)]
    public string taxAreaCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=11)]
    public string taxRegistrationNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=12)]
    public string city;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=13)]
    public string faxNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=14)]
    public string email;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=15)]
    public string webSite;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=16)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime bilgitasInvoiceDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=17)]
    public string bilgitasInvoiceNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=18)]
    public string invoiceNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=19)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime setupDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=20)]
    public string description;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=21)]
    public bool governmentAgency;
    
    public InsertSellout()
    {
    }
    
    public InsertSellout(
                string customerNo, 
                string itemNo, 
                decimal quantity, 
                string name, 
                string contactName, 
                string address, 
                string address2, 
                string phoneNo, 
                System.DateTime invoiceDate, 
                string serialNo, 
                string taxAreaCode, 
                string taxRegistrationNo, 
                string city, 
                string faxNo, 
                string email, 
                string webSite, 
                System.DateTime bilgitasInvoiceDate, 
                string bilgitasInvoiceNo, 
                string invoiceNo, 
                System.DateTime setupDate, 
                string description, 
                bool governmentAgency)
    {
        this.customerNo = customerNo;
        this.itemNo = itemNo;
        this.quantity = quantity;
        this.name = name;
        this.contactName = contactName;
        this.address = address;
        this.address2 = address2;
        this.phoneNo = phoneNo;
        this.invoiceDate = invoiceDate;
        this.serialNo = serialNo;
        this.taxAreaCode = taxAreaCode;
        this.taxRegistrationNo = taxRegistrationNo;
        this.city = city;
        this.faxNo = faxNo;
        this.email = email;
        this.webSite = webSite;
        this.bilgitasInvoiceDate = bilgitasInvoiceDate;
        this.bilgitasInvoiceNo = bilgitasInvoiceNo;
        this.invoiceNo = invoiceNo;
        this.setupDate = setupDate;
        this.description = description;
        this.governmentAgency = governmentAgency;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="InsertSellout_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class InsertSellout_Result
{
    
    public InsertSellout_Result()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSellout", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class DeleteSellout
{
    
    public DeleteSellout()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSellout_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class DeleteSellout_Result
{
    
    public DeleteSellout_Result()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="EnterCounter", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class EnterCounter
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string pServDevNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public int pCounterSB;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public int pCounterRK;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime pDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    public string pExplanation;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=5)]
    public int pYear;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=6)]
    public int pMonth;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=7)]
    public int pFirstSB;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=8)]
    public int pFirstRK;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=9)]
    public string pBayiNo;
    
    public EnterCounter()
    {
    }
    
    public EnterCounter(string pServDevNo, int pCounterSB, int pCounterRK, System.DateTime pDate, string pExplanation, int pYear, int pMonth, int pFirstSB, int pFirstRK, string pBayiNo)
    {
        this.pServDevNo = pServDevNo;
        this.pCounterSB = pCounterSB;
        this.pCounterRK = pCounterRK;
        this.pDate = pDate;
        this.pExplanation = pExplanation;
        this.pYear = pYear;
        this.pMonth = pMonth;
        this.pFirstSB = pFirstSB;
        this.pFirstRK = pFirstRK;
        this.pBayiNo = pBayiNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="EnterCounter_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class EnterCounter_Result
{
    
    public EnterCounter_Result()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateSOfromWB", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateSOfromWB
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime postingDate;
    
    public CreateSOfromWB()
    {
    }
    
    public CreateSOfromWB(System.DateTime postingDate)
    {
        this.postingDate = postingDate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateSOfromWB_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateSOfromWB_Result
{
    
    public CreateSOfromWB_Result()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateSOfromWBforUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateSOfromWBforUser
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string pCustomerNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string pShiptoCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public string pLocationCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public int pPriceType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime postingDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=5)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime pDocumentDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=6)]
    public bool pCalculateDueDate;
    
    public CreateSOfromWBforUser()
    {
    }
    
    public CreateSOfromWBforUser(string pCustomerNo, string pShiptoCode, string pLocationCode, int pPriceType, System.DateTime postingDate, System.DateTime pDocumentDate, bool pCalculateDueDate)
    {
        this.pCustomerNo = pCustomerNo;
        this.pShiptoCode = pShiptoCode;
        this.pLocationCode = pLocationCode;
        this.pPriceType = pPriceType;
        this.postingDate = postingDate;
        this.pDocumentDate = pDocumentDate;
        this.pCalculateDueDate = pCalculateDueDate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateSOfromWBforUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateSOfromWBforUser_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string return_value;
    
    public CreateSOfromWBforUser_Result()
    {
    }
    
    public CreateSOfromWBforUser_Result(string return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateTOfromWBforUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateTOfromWBforUser
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string pCustomerNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string pShiptoCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public string pLocationCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime postingDate;
    
    public CreateTOfromWBforUser()
    {
    }
    
    public CreateTOfromWBforUser(string pCustomerNo, string pShiptoCode, string pLocationCode, System.DateTime postingDate)
    {
        this.pCustomerNo = pCustomerNo;
        this.pShiptoCode = pShiptoCode;
        this.pLocationCode = pLocationCode;
        this.postingDate = postingDate;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateTOfromWBforUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateTOfromWBforUser_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string return_value;
    
    public CreateTOfromWBforUser_Result()
    {
    }
    
    public CreateTOfromWBforUser_Result(string return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateAntrepo", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateAntrepo
{
    
    public CreateAntrepo()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateAntrepo_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateAntrepo_Result
{
    
    public CreateAntrepo_Result()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="HashPassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class HashPassword
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string passwordp;
    
    public HashPassword()
    {
    }
    
    public HashPassword(string passwordp)
    {
        this.passwordp = passwordp;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="HashPassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class HashPassword_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string return_value;
    
    public HashPassword_Result()
    {
    }
    
    public HashPassword_Result(string return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUser", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class ValidateUser
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string companyp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string userIDp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public string passwordp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public bool resetPasswordp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    public string customerNop;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=5)]
    public int webVisibilityp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=6)]
    [System.Xml.Serialization.XmlElementAttribute("eMails")]
    public string[] eMails;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=7)]
    public string namep;
    
    public ValidateUser()
    {
    }
    
    public ValidateUser(string companyp, string userIDp, string passwordp, bool resetPasswordp, string customerNop, int webVisibilityp, string[] eMails, string namep)
    {
        this.companyp = companyp;
        this.userIDp = userIDp;
        this.passwordp = passwordp;
        this.resetPasswordp = resetPasswordp;
        this.customerNop = customerNop;
        this.webVisibilityp = webVisibilityp;
        this.eMails = eMails;
        this.namep = namep;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUser_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class ValidateUser_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public bool return_value;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public bool resetPasswordp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public string customerNop;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public int webVisibilityp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    [System.Xml.Serialization.XmlElementAttribute("eMails")]
    public string[] eMails;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=5)]
    public string namep;
    
    public ValidateUser_Result()
    {
    }
    
    public ValidateUser_Result(bool return_value, bool resetPasswordp, string customerNop, int webVisibilityp, string[] eMails, string namep)
    {
        this.return_value = return_value;
        this.resetPasswordp = resetPasswordp;
        this.customerNop = customerNop;
        this.webVisibilityp = webVisibilityp;
        this.eMails = eMails;
        this.namep = namep;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class ChangePassword
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string companyp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string userIDp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public string passwordp;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public string newPasswordp;
    
    public ChangePassword()
    {
    }
    
    public ChangePassword(string companyp, string userIDp, string passwordp, string newPasswordp)
    {
        this.companyp = companyp;
        this.userIDp = userIDp;
        this.passwordp = passwordp;
        this.newPasswordp = newPasswordp;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class ChangePassword_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public bool return_value;
    
    public ChangePassword_Result()
    {
    }
    
    public ChangePassword_Result(bool return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RandomChangePassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class RandomChangePassword
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string userIDp;
    
    public RandomChangePassword()
    {
    }
    
    public RandomChangePassword(string userIDp)
    {
        this.userIDp = userIDp;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RandomChangePassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class RandomChangePassword_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public bool return_value;
    
    public RandomChangePassword_Result()
    {
    }
    
    public RandomChangePassword_Result(bool return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmWebBasket", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class ConfirmWebBasket
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string userIDp;
    
    public ConfirmWebBasket()
    {
    }
    
    public ConfirmWebBasket(string userIDp)
    {
        this.userIDp = userIDp;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmWebBasket_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class ConfirmWebBasket_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public bool return_value;
    
    public ConfirmWebBasket_Result()
    {
    }
    
    public ConfirmWebBasket_Result(bool return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="FindItemSerial", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class FindItemSerial
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string pSerialNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string pDealerNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public string pUserID;
    
    public FindItemSerial()
    {
    }
    
    public FindItemSerial(string pSerialNo, string pDealerNo, string pUserID)
    {
        this.pSerialNo = pSerialNo;
        this.pDealerNo = pDealerNo;
        this.pUserID = pUserID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="FindItemSerial_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class FindItemSerial_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public int return_value;
    
    public FindItemSerial_Result()
    {
    }
    
    public FindItemSerial_Result(int return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateWarReqEntry", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateWarReqEntry
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string pResellerNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string pSoldtoCustomerName;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime pSetupDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public string pItemNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    public string pSerialNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=5)]
    public string pUserID;
    
    public CreateWarReqEntry()
    {
    }
    
    public CreateWarReqEntry(string pResellerNo, string pSoldtoCustomerName, System.DateTime pSetupDate, string pItemNo, string pSerialNo, string pUserID)
    {
        this.pResellerNo = pResellerNo;
        this.pSoldtoCustomerName = pSoldtoCustomerName;
        this.pSetupDate = pSetupDate;
        this.pItemNo = pItemNo;
        this.pSerialNo = pSerialNo;
        this.pUserID = pUserID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateWarReqEntry_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateWarReqEntry_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public int return_value;
    
    public CreateWarReqEntry_Result()
    {
    }
    
    public CreateWarReqEntry_Result(int return_value)
    {
        this.return_value = return_value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWarReqEntry", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class UpdateWarReqEntry
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public int pEntryNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    public string pSpareItemNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    public string pSpareOldSerialNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public string pSpareNewSerialNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime pRepairDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=5)]
    public int pNumaratoratProblem;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=6)]
    public int pNumaratoratRepair;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=7)]
    public string pProblemCode;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=8)]
    public string pProblemDescription;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=9)]
    public string pUserID;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=10)]
    public string pReferenceNo;
    
    public UpdateWarReqEntry()
    {
    }
    
    public UpdateWarReqEntry(int pEntryNo, string pSpareItemNo, string pSpareOldSerialNo, string pSpareNewSerialNo, System.DateTime pRepairDate, int pNumaratoratProblem, int pNumaratoratRepair, string pProblemCode, string pProblemDescription, string pUserID, string pReferenceNo)
    {
        this.pEntryNo = pEntryNo;
        this.pSpareItemNo = pSpareItemNo;
        this.pSpareOldSerialNo = pSpareOldSerialNo;
        this.pSpareNewSerialNo = pSpareNewSerialNo;
        this.pRepairDate = pRepairDate;
        this.pNumaratoratProblem = pNumaratoratProblem;
        this.pNumaratoratRepair = pNumaratoratRepair;
        this.pProblemCode = pProblemCode;
        this.pProblemDescription = pProblemDescription;
        this.pUserID = pUserID;
        this.pReferenceNo = pReferenceNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="UpdateWarReqEntry_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class UpdateWarReqEntry_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string pReferenceNo;
    
    public UpdateWarReqEntry_Result()
    {
    }
    
    public UpdateWarReqEntry_Result(string pReferenceNo)
    {
        this.pReferenceNo = pReferenceNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateReport_50018", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateReport_50018
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string customerNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime startDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime endDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public string reportType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    public string fileContent;
    
    public CreateReport_50018()
    {
    }
    
    public CreateReport_50018(string customerNo, System.DateTime startDate, System.DateTime endDate, string reportType, string fileContent)
    {
        this.customerNo = customerNo;
        this.startDate = startDate;
        this.endDate = endDate;
        this.reportType = reportType;
        this.fileContent = fileContent;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateReport_50018_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateReport_50018_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string fileContent;
    
    public CreateReport_50018_Result()
    {
    }
    
    public CreateReport_50018_Result(string fileContent)
    {
        this.fileContent = fileContent;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateReport_50162", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateReport_50162
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string customerNo;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime startDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime endDate;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=3)]
    public string reportType;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=4)]
    public string fileContent;
    
    public CreateReport_50162()
    {
    }
    
    public CreateReport_50162(string customerNo, System.DateTime startDate, System.DateTime endDate, string reportType, string fileContent)
    {
        this.customerNo = customerNo;
        this.startDate = startDate;
        this.endDate = endDate;
        this.reportType = reportType;
        this.fileContent = fileContent;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="CreateReport_50162_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class CreateReport_50162_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string fileContent;
    
    public CreateReport_50162_Result()
    {
    }
    
    public CreateReport_50162_Result(string fileContent)
    {
        this.fileContent = fileContent;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendResourcePassword", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class SendResourcePassword
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public string userIDp;
    
    public SendResourcePassword()
    {
    }
    
    public SendResourcePassword(string userIDp)
    {
        this.userIDp = userIDp;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="SendResourcePassword_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", IsWrapped=true)]
public partial class SendResourcePassword_Result
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/WebManagement", Order=0)]
    public bool return_value;
    
    public SendResourcePassword_Result()
    {
    }
    
    public SendResourcePassword_Result(bool return_value)
    {
        this.return_value = return_value;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface WebManagement_PortChannel : WebManagement_Port, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class WebManagement_PortClient : System.ServiceModel.ClientBase<WebManagement_Port>, WebManagement_Port
{
    
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
    
    public WebManagement_PortClient() : 
            base(WebManagement_PortClient.GetDefaultBinding(), WebManagement_PortClient.GetDefaultEndpointAddress())
    {
        this.Endpoint.Name = EndpointConfiguration.WebManagement_Port.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebManagement_PortClient(EndpointConfiguration endpointConfiguration) : 
            base(WebManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), WebManagement_PortClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebManagement_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
            base(WebManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebManagement_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(WebManagement_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }
    
    public WebManagement_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<InsertWebBasket_Result> WebManagement_Port.InsertWebBasketAsync(InsertWebBasket request)
    {
        return base.Channel.InsertWebBasketAsync(request);
    }
    
    public System.Threading.Tasks.Task<InsertWebBasket_Result> InsertWebBasketAsync(string aUserID, string itemNo, decimal quantity, string salesDescription)
    {
        InsertWebBasket inValue = new InsertWebBasket();
        inValue.aUserID = aUserID;
        inValue.itemNo = itemNo;
        inValue.quantity = quantity;
        inValue.salesDescription = salesDescription;
        return ((WebManagement_Port)(this)).InsertWebBasketAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<DeleteWebBasket_Result> WebManagement_Port.DeleteWebBasketAsync(DeleteWebBasket request)
    {
        return base.Channel.DeleteWebBasketAsync(request);
    }
    
    public System.Threading.Tasks.Task<DeleteWebBasket_Result> DeleteWebBasketAsync()
    {
        DeleteWebBasket inValue = new DeleteWebBasket();
        return ((WebManagement_Port)(this)).DeleteWebBasketAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<InsertSellout_Result> WebManagement_Port.InsertSelloutAsync(InsertSellout request)
    {
        return base.Channel.InsertSelloutAsync(request);
    }
    
    public System.Threading.Tasks.Task<InsertSellout_Result> InsertSelloutAsync(
                string customerNo, 
                string itemNo, 
                decimal quantity, 
                string name, 
                string contactName, 
                string address, 
                string address2, 
                string phoneNo, 
                System.DateTime invoiceDate, 
                string serialNo, 
                string taxAreaCode, 
                string taxRegistrationNo, 
                string city, 
                string faxNo, 
                string email, 
                string webSite, 
                System.DateTime bilgitasInvoiceDate, 
                string bilgitasInvoiceNo, 
                string invoiceNo, 
                System.DateTime setupDate, 
                string description, 
                bool governmentAgency)
    {
        InsertSellout inValue = new InsertSellout();
        inValue.customerNo = customerNo;
        inValue.itemNo = itemNo;
        inValue.quantity = quantity;
        inValue.name = name;
        inValue.contactName = contactName;
        inValue.address = address;
        inValue.address2 = address2;
        inValue.phoneNo = phoneNo;
        inValue.invoiceDate = invoiceDate;
        inValue.serialNo = serialNo;
        inValue.taxAreaCode = taxAreaCode;
        inValue.taxRegistrationNo = taxRegistrationNo;
        inValue.city = city;
        inValue.faxNo = faxNo;
        inValue.email = email;
        inValue.webSite = webSite;
        inValue.bilgitasInvoiceDate = bilgitasInvoiceDate;
        inValue.bilgitasInvoiceNo = bilgitasInvoiceNo;
        inValue.invoiceNo = invoiceNo;
        inValue.setupDate = setupDate;
        inValue.description = description;
        inValue.governmentAgency = governmentAgency;
        return ((WebManagement_Port)(this)).InsertSelloutAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<DeleteSellout_Result> WebManagement_Port.DeleteSelloutAsync(DeleteSellout request)
    {
        return base.Channel.DeleteSelloutAsync(request);
    }
    
    public System.Threading.Tasks.Task<DeleteSellout_Result> DeleteSelloutAsync()
    {
        DeleteSellout inValue = new DeleteSellout();
        return ((WebManagement_Port)(this)).DeleteSelloutAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<EnterCounter_Result> WebManagement_Port.EnterCounterAsync(EnterCounter request)
    {
        return base.Channel.EnterCounterAsync(request);
    }
    
    public System.Threading.Tasks.Task<EnterCounter_Result> EnterCounterAsync(string pServDevNo, int pCounterSB, int pCounterRK, System.DateTime pDate, string pExplanation, int pYear, int pMonth, int pFirstSB, int pFirstRK, string pBayiNo)
    {
        EnterCounter inValue = new EnterCounter();
        inValue.pServDevNo = pServDevNo;
        inValue.pCounterSB = pCounterSB;
        inValue.pCounterRK = pCounterRK;
        inValue.pDate = pDate;
        inValue.pExplanation = pExplanation;
        inValue.pYear = pYear;
        inValue.pMonth = pMonth;
        inValue.pFirstSB = pFirstSB;
        inValue.pFirstRK = pFirstRK;
        inValue.pBayiNo = pBayiNo;
        return ((WebManagement_Port)(this)).EnterCounterAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateSOfromWB_Result> WebManagement_Port.CreateSOfromWBAsync(CreateSOfromWB request)
    {
        return base.Channel.CreateSOfromWBAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateSOfromWB_Result> CreateSOfromWBAsync(System.DateTime postingDate)
    {
        CreateSOfromWB inValue = new CreateSOfromWB();
        inValue.postingDate = postingDate;
        return ((WebManagement_Port)(this)).CreateSOfromWBAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateSOfromWBforUser_Result> WebManagement_Port.CreateSOfromWBforUserAsync(CreateSOfromWBforUser request)
    {
        return base.Channel.CreateSOfromWBforUserAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateSOfromWBforUser_Result> CreateSOfromWBforUserAsync(string pCustomerNo, string pShiptoCode, string pLocationCode, int pPriceType, System.DateTime postingDate, System.DateTime pDocumentDate, bool pCalculateDueDate)
    {
        CreateSOfromWBforUser inValue = new CreateSOfromWBforUser();
        inValue.pCustomerNo = pCustomerNo;
        inValue.pShiptoCode = pShiptoCode;
        inValue.pLocationCode = pLocationCode;
        inValue.pPriceType = pPriceType;
        inValue.postingDate = postingDate;
        inValue.pDocumentDate = pDocumentDate;
        inValue.pCalculateDueDate = pCalculateDueDate;
        return ((WebManagement_Port)(this)).CreateSOfromWBforUserAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateTOfromWBforUser_Result> WebManagement_Port.CreateTOfromWBforUserAsync(CreateTOfromWBforUser request)
    {
        return base.Channel.CreateTOfromWBforUserAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateTOfromWBforUser_Result> CreateTOfromWBforUserAsync(string pCustomerNo, string pShiptoCode, string pLocationCode, System.DateTime postingDate)
    {
        CreateTOfromWBforUser inValue = new CreateTOfromWBforUser();
        inValue.pCustomerNo = pCustomerNo;
        inValue.pShiptoCode = pShiptoCode;
        inValue.pLocationCode = pLocationCode;
        inValue.postingDate = postingDate;
        return ((WebManagement_Port)(this)).CreateTOfromWBforUserAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateAntrepo_Result> WebManagement_Port.CreateAntrepoAsync(CreateAntrepo request)
    {
        return base.Channel.CreateAntrepoAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateAntrepo_Result> CreateAntrepoAsync()
    {
        CreateAntrepo inValue = new CreateAntrepo();
        return ((WebManagement_Port)(this)).CreateAntrepoAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<HashPassword_Result> WebManagement_Port.HashPasswordAsync(HashPassword request)
    {
        return base.Channel.HashPasswordAsync(request);
    }
    
    public System.Threading.Tasks.Task<HashPassword_Result> HashPasswordAsync(string passwordp)
    {
        HashPassword inValue = new HashPassword();
        inValue.passwordp = passwordp;
        return ((WebManagement_Port)(this)).HashPasswordAsync(inValue);
    }
    
    public System.Threading.Tasks.Task<ValidateUser_Result> ValidateUserAsync(ValidateUser request)
    {
        return base.Channel.ValidateUserAsync(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ChangePassword_Result> WebManagement_Port.ChangePasswordAsync(ChangePassword request)
    {
        return base.Channel.ChangePasswordAsync(request);
    }
    
    public System.Threading.Tasks.Task<ChangePassword_Result> ChangePasswordAsync(string companyp, string userIDp, string passwordp, string newPasswordp)
    {
        ChangePassword inValue = new ChangePassword();
        inValue.companyp = companyp;
        inValue.userIDp = userIDp;
        inValue.passwordp = passwordp;
        inValue.newPasswordp = newPasswordp;
        return ((WebManagement_Port)(this)).ChangePasswordAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<RandomChangePassword_Result> WebManagement_Port.RandomChangePasswordAsync(RandomChangePassword request)
    {
        return base.Channel.RandomChangePasswordAsync(request);
    }
    
    public System.Threading.Tasks.Task<RandomChangePassword_Result> RandomChangePasswordAsync(string userIDp)
    {
        RandomChangePassword inValue = new RandomChangePassword();
        inValue.userIDp = userIDp;
        return ((WebManagement_Port)(this)).RandomChangePasswordAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<ConfirmWebBasket_Result> WebManagement_Port.ConfirmWebBasketAsync(ConfirmWebBasket request)
    {
        return base.Channel.ConfirmWebBasketAsync(request);
    }
    
    public System.Threading.Tasks.Task<ConfirmWebBasket_Result> ConfirmWebBasketAsync(string userIDp)
    {
        ConfirmWebBasket inValue = new ConfirmWebBasket();
        inValue.userIDp = userIDp;
        return ((WebManagement_Port)(this)).ConfirmWebBasketAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<FindItemSerial_Result> WebManagement_Port.FindItemSerialAsync(FindItemSerial request)
    {
        return base.Channel.FindItemSerialAsync(request);
    }
    
    public System.Threading.Tasks.Task<FindItemSerial_Result> FindItemSerialAsync(string pSerialNo, string pDealerNo, string pUserID)
    {
        FindItemSerial inValue = new FindItemSerial();
        inValue.pSerialNo = pSerialNo;
        inValue.pDealerNo = pDealerNo;
        inValue.pUserID = pUserID;
        return ((WebManagement_Port)(this)).FindItemSerialAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateWarReqEntry_Result> WebManagement_Port.CreateWarReqEntryAsync(CreateWarReqEntry request)
    {
        return base.Channel.CreateWarReqEntryAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateWarReqEntry_Result> CreateWarReqEntryAsync(string pResellerNo, string pSoldtoCustomerName, System.DateTime pSetupDate, string pItemNo, string pSerialNo, string pUserID)
    {
        CreateWarReqEntry inValue = new CreateWarReqEntry();
        inValue.pResellerNo = pResellerNo;
        inValue.pSoldtoCustomerName = pSoldtoCustomerName;
        inValue.pSetupDate = pSetupDate;
        inValue.pItemNo = pItemNo;
        inValue.pSerialNo = pSerialNo;
        inValue.pUserID = pUserID;
        return ((WebManagement_Port)(this)).CreateWarReqEntryAsync(inValue);
    }
    
    public System.Threading.Tasks.Task<UpdateWarReqEntry_Result> UpdateWarReqEntryAsync(UpdateWarReqEntry request)
    {
        return base.Channel.UpdateWarReqEntryAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateReport_50018_Result> CreateReport_50018Async(CreateReport_50018 request)
    {
        return base.Channel.CreateReport_50018Async(request);
    }
    
    public System.Threading.Tasks.Task<CreateReport_50162_Result> CreateReport_50162Async(CreateReport_50162 request)
    {
        return base.Channel.CreateReport_50162Async(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SendResourcePassword_Result> WebManagement_Port.SendResourcePasswordAsync(SendResourcePassword request)
    {
        return base.Channel.SendResourcePasswordAsync(request);
    }
    
    public System.Threading.Tasks.Task<SendResourcePassword_Result> SendResourcePasswordAsync(string userIDp)
    {
        SendResourcePassword inValue = new SendResourcePassword();
        inValue.userIDp = userIDp;
        return ((WebManagement_Port)(this)).SendResourcePasswordAsync(inValue);
    }
    
    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }
    
    #if !NET6_0_OR_GREATER
    public virtual System.Threading.Tasks.Task CloseAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
    }
    #endif
    
    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.WebManagement_Port))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.WebManagement_Port))
        {
            return new System.ServiceModel.EndpointAddress("http://192.168.100.5:9047/DTRKYOCERA/WS/Bilgitas/Codeunit/WebManagement?wsdl");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }
    
    private static System.ServiceModel.Channels.Binding GetDefaultBinding()
    {
        return WebManagement_PortClient.GetBindingForEndpoint(EndpointConfiguration.WebManagement_Port);
    }
    
    private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
    {
        return WebManagement_PortClient.GetEndpointAddress(EndpointConfiguration.WebManagement_Port);
    }
    
    public enum EndpointConfiguration
    {
        
        WebManagement_Port,
    }
}
